// frontend/src/components/Navbar.tsx
// src/components/Navbar.tsx
import React from 'react';
import { Link } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
import logo from '../assets/image (3).png';


const Navbar: React.FC = () => {
    const { isAuthenticated, logout, user } = useAuth();

    const handleLogout = () => {
        logout(); // Call logout from context
    };

    return (
        <nav className="flex justify-between items-center p-4 bg-black shadow-md w-full">
            <div className="flex items-center">
        <a href='/'><img src={logo} alt="Digital Chit Fund Management Logo" className="md:h-12 lg:h-14 ml-7" /></a> {/* Adjust 'h-10' for logo size */}
        <span className="ml-3 text-lg font-semibold">Digital Chit Fund Management</span>
      </div>
            <div className="space-x-6 flex items-center">
                <Link to="/chitplans" className="text-gray-300 hover:text-white">Chit Plans</Link>
                {isAuthenticated && (
                    <><Link to="/mygroups" className="text-gray-300 hover:text-white">My Groups</Link>
                    <Link to="/mytransactions" className="text-gray-300 hover:text-white">My Transactions</Link>
                    <Link to="/profile" className="text-gray-300 hover:text-white">Profile</Link></>
                )}

                {isAuthenticated && user?.userRole === 'admin' && (
                    <Link to="/admin" className="text-gray-300 hover:text-white">
                        Admin Dashboard
                    </Link>
                )}

                {isAuthenticated ? (
                    <Link to="/">
                    <button 
                        onClick={handleLogout} 
                        className="px-4 py-1 border border-gray-500 text-gray-300 rounded-md hover:bg-gray-700 hover:text-white transition-colors duration-200"
                    >
                        Logout
                    </button>
                    </Link>
                ) : (
                    <>
                        <Link to="/login">
                            <button className="px-4 py-1 border border-gray-500 text-gray-300 rounded-md hover:bg-gray-700 hover:text-white transition-colors duration-200">
                                Log In
                            </button>
                        </Link>
                        <Link to="/register">
                            <button className="px-4 py-1 bg-indigo-800 text-white rounded-md hover:bg-indigo-400 transition-colors duration-200">
                                Register
                            </button>
                        </Link>
                    </>
                )}
            </div>
        </nav>
    );
};

export default Navbar;

// frontend-ang/src/app/navbar/navbar.component.ts
import { CommonModule } from '@angular/common';
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { AuthService } from '../../auth/auth.service';

@Component({
  selector: 'app-navbar',
  imports: [CommonModule],
  templateUrl: './navbar.component.html',
  styleUrls: ['./navbar.component.css'],
})
export class NavbarComponent implements OnInit {
  isAuthenticated = false;
isLoggedIn: any;
user: any;

  constructor(private authService: AuthService, private router: Router) {}

  ngOnInit(): void {
    this.authService.user$.subscribe((user) => {
      this.isAuthenticated = !!user;
      // Add a delay before updating the isAuthenticated state
      // setTimeout(() => {
      //   this.isAuthenticated = !!user;
      // }, 1000); 
    });
  }

  handleLogout(): void {
    this.authService.logout();
    this.router.navigate(['/']); // Redirect to home page after logout
  }
}

<nav class="flex justify-between items-center p-4 bg-black shadow-md w-full">
  <div class="flex items-center">
    <a href="/">
      <img src="image (3).png" alt="Logo" class="md:h-12 lg:h-14 ml-7" />
    </a>
    <!-- <span class="ml-3 text-lg font-semibold text-white">Digital Chit Fund Management</span> -->
  </div>

  <div class="space-x-6 flex items-center">
    <a href="/chitplans" class="text-gray-300 hover:text-white">Chit Plans</a>

    <ng-container *ngIf="isAuthenticated">
      <a href="/mygroups" class="text-gray-300 hover:text-white">My Groups</a>
      <a href="/mytransactions" class="text-gray-300 hover:text-white">My Transactions</a>
      <a href="/profile" class="text-gray-300 hover:text-white">Profile</a>
      <button 
        (click)="handleLogout()" 
        class="px-4 py-1 border border-gray-500 text-gray-300 rounded-md hover:bg-gray-700 hover:text-white transition-colors duration-200">
        Logout
      </button>
    </ng-container>

    <ng-container *ngIf="!isAuthenticated">
      <a href="/login">
        <button class="px-4 py-1 border border-gray-500 text-gray-300 rounded-md hover:bg-gray-700 hover:text-white transition-colors duration-200">
          Log In
        </button>
      </a>
      <a href="/register">
        <button class="px-4 py-1 bg-indigo-800 text-white rounded-md hover:bg-indigo-400 transition-colors duration-200">
          Register
        </button>
      </a>
    </ng-container>
  </div>

  <li class="nav-item" *ngIf="isLoggedIn && user?.userRole === 'participant'">
    <a class="nav-link" routerLink="/dashboard" routerLinkActive="active">Dashboard</a>
  </li>

</nav>
